/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.replicationdata.Status', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.replicationdata.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.replicationdata.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.replicationdata.Status.displayName = 'proto.replicationdata.Status';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.replicationdata.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.replicationdata.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.replicationdata.Status} msg The msg instance to transform.
 * @return {!Object}
 */
proto.replicationdata.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
    position: jspb.Message.getFieldWithDefault(msg, 1, ""),
    slaveIoRunning: jspb.Message.getFieldWithDefault(msg, 2, false),
    slaveSqlRunning: jspb.Message.getFieldWithDefault(msg, 3, false),
    secondsBehindMaster: jspb.Message.getFieldWithDefault(msg, 4, 0),
    masterHost: jspb.Message.getFieldWithDefault(msg, 5, ""),
    masterPort: jspb.Message.getFieldWithDefault(msg, 6, 0),
    masterConnectRetry: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.replicationdata.Status}
 */
proto.replicationdata.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.replicationdata.Status;
  return proto.replicationdata.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.replicationdata.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.replicationdata.Status}
 */
proto.replicationdata.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPosition(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSlaveIoRunning(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSlaveSqlRunning(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSecondsBehindMaster(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMasterHost(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMasterPort(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMasterConnectRetry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.replicationdata.Status} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.replicationdata.Status.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.replicationdata.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.replicationdata.Status.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPosition();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSlaveIoRunning();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = this.getSlaveSqlRunning();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = this.getSecondsBehindMaster();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = this.getMasterHost();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getMasterPort();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = this.getMasterConnectRetry();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional string position = 1;
 * @return {string}
 */
proto.replicationdata.Status.prototype.getPosition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.replicationdata.Status.prototype.setPosition = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bool slave_io_running = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.replicationdata.Status.prototype.getSlaveIoRunning = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.replicationdata.Status.prototype.setSlaveIoRunning = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool slave_sql_running = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.replicationdata.Status.prototype.getSlaveSqlRunning = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.replicationdata.Status.prototype.setSlaveSqlRunning = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint32 seconds_behind_master = 4;
 * @return {number}
 */
proto.replicationdata.Status.prototype.getSecondsBehindMaster = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.replicationdata.Status.prototype.setSecondsBehindMaster = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string master_host = 5;
 * @return {string}
 */
proto.replicationdata.Status.prototype.getMasterHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.replicationdata.Status.prototype.setMasterHost = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional int32 master_port = 6;
 * @return {number}
 */
proto.replicationdata.Status.prototype.getMasterPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.replicationdata.Status.prototype.setMasterPort = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional int32 master_connect_retry = 7;
 * @return {number}
 */
proto.replicationdata.Status.prototype.getMasterConnectRetry = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.replicationdata.Status.prototype.setMasterConnectRetry = function(value) {
  jspb.Message.setField(this, 7, value);
};


goog.object.extend(exports, proto.replicationdata);
