/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.tableacl.Config', null, global);
goog.exportSymbol('proto.tableacl.TableGroupSpec', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tableacl.TableGroupSpec = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tableacl.TableGroupSpec.repeatedFields_, null);
};
goog.inherits(proto.tableacl.TableGroupSpec, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tableacl.TableGroupSpec.displayName = 'proto.tableacl.TableGroupSpec';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tableacl.TableGroupSpec.repeatedFields_ = [2,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tableacl.TableGroupSpec.prototype.toObject = function(opt_includeInstance) {
  return proto.tableacl.TableGroupSpec.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tableacl.TableGroupSpec} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tableacl.TableGroupSpec.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tableNamesOrPrefixesList: jspb.Message.getField(msg, 2),
    readersList: jspb.Message.getField(msg, 3),
    writersList: jspb.Message.getField(msg, 4),
    adminsList: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tableacl.TableGroupSpec}
 */
proto.tableacl.TableGroupSpec.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tableacl.TableGroupSpec;
  return proto.tableacl.TableGroupSpec.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tableacl.TableGroupSpec} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tableacl.TableGroupSpec}
 */
proto.tableacl.TableGroupSpec.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addTableNamesOrPrefixes(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addReaders(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addWriters(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addAdmins(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.tableacl.TableGroupSpec} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tableacl.TableGroupSpec.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tableacl.TableGroupSpec.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.tableacl.TableGroupSpec.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getTableNamesOrPrefixesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = this.getReadersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = this.getWritersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = this.getAdminsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.tableacl.TableGroupSpec.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tableacl.TableGroupSpec.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated string table_names_or_prefixes = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.tableacl.TableGroupSpec.prototype.getTableNamesOrPrefixesList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 2));
};


/** @param {!Array.<string>} value */
proto.tableacl.TableGroupSpec.prototype.setTableNamesOrPrefixesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.tableacl.TableGroupSpec.prototype.addTableNamesOrPrefixes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.tableacl.TableGroupSpec.prototype.clearTableNamesOrPrefixesList = function() {
  this.setTableNamesOrPrefixesList([]);
};


/**
 * repeated string readers = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.tableacl.TableGroupSpec.prototype.getReadersList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 3));
};


/** @param {!Array.<string>} value */
proto.tableacl.TableGroupSpec.prototype.setReadersList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.tableacl.TableGroupSpec.prototype.addReaders = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.tableacl.TableGroupSpec.prototype.clearReadersList = function() {
  this.setReadersList([]);
};


/**
 * repeated string writers = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.tableacl.TableGroupSpec.prototype.getWritersList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 4));
};


/** @param {!Array.<string>} value */
proto.tableacl.TableGroupSpec.prototype.setWritersList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.tableacl.TableGroupSpec.prototype.addWriters = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


proto.tableacl.TableGroupSpec.prototype.clearWritersList = function() {
  this.setWritersList([]);
};


/**
 * repeated string admins = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.tableacl.TableGroupSpec.prototype.getAdminsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 5));
};


/** @param {!Array.<string>} value */
proto.tableacl.TableGroupSpec.prototype.setAdminsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.tableacl.TableGroupSpec.prototype.addAdmins = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.tableacl.TableGroupSpec.prototype.clearAdminsList = function() {
  this.setAdminsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tableacl.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tableacl.Config.repeatedFields_, null);
};
goog.inherits(proto.tableacl.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tableacl.Config.displayName = 'proto.tableacl.Config';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tableacl.Config.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tableacl.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.tableacl.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tableacl.Config} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tableacl.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    tableGroupsList: jspb.Message.toObjectList(msg.getTableGroupsList(),
    proto.tableacl.TableGroupSpec.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tableacl.Config}
 */
proto.tableacl.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tableacl.Config;
  return proto.tableacl.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tableacl.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tableacl.Config}
 */
proto.tableacl.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tableacl.TableGroupSpec;
      reader.readMessage(value,proto.tableacl.TableGroupSpec.deserializeBinaryFromReader);
      msg.addTableGroups(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.tableacl.Config} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tableacl.Config.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tableacl.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.tableacl.Config.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getTableGroupsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.tableacl.TableGroupSpec.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TableGroupSpec table_groups = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.tableacl.TableGroupSpec>}
 */
proto.tableacl.Config.prototype.getTableGroupsList = function() {
  return /** @type{!Array.<!proto.tableacl.TableGroupSpec>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tableacl.TableGroupSpec, 1));
};


/** @param {!Array.<!proto.tableacl.TableGroupSpec>} value */
proto.tableacl.Config.prototype.setTableGroupsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tableacl.TableGroupSpec=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tableacl.TableGroupSpec}
 */
proto.tableacl.Config.prototype.addTableGroups = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tableacl.TableGroupSpec, opt_index);
};


proto.tableacl.Config.prototype.clearTableGroupsList = function() {
  this.setTableGroupsList([]);
};


goog.object.extend(exports, proto.tableacl);
