/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var logutil_pb = require('./logutil_pb.js');
goog.exportSymbol('proto.vtctldata.ExecuteVtctlCommandRequest', null, global);
goog.exportSymbol('proto.vtctldata.ExecuteVtctlCommandResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vtctldata.ExecuteVtctlCommandRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vtctldata.ExecuteVtctlCommandRequest.repeatedFields_, null);
};
goog.inherits(proto.vtctldata.ExecuteVtctlCommandRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.vtctldata.ExecuteVtctlCommandRequest.displayName = 'proto.vtctldata.ExecuteVtctlCommandRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vtctldata.ExecuteVtctlCommandRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.vtctldata.ExecuteVtctlCommandRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vtctldata.ExecuteVtctlCommandRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    argsList: jspb.Message.getField(msg, 1),
    actionTimeout: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vtctldata.ExecuteVtctlCommandRequest}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vtctldata.ExecuteVtctlCommandRequest;
  return proto.vtctldata.ExecuteVtctlCommandRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vtctldata.ExecuteVtctlCommandRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vtctldata.ExecuteVtctlCommandRequest}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addArgs(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setActionTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.vtctldata.ExecuteVtctlCommandRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtctldata.ExecuteVtctlCommandRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getArgsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = this.getActionTimeout();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated string args = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.getArgsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 1));
};


/** @param {!Array.<string>} value */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.setArgsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.addArgs = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.vtctldata.ExecuteVtctlCommandRequest.prototype.clearArgsList = function() {
  this.setArgsList([]);
};


/**
 * optional int64 action_timeout = 2;
 * @return {number}
 */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.getActionTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.vtctldata.ExecuteVtctlCommandRequest.prototype.setActionTimeout = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vtctldata.ExecuteVtctlCommandResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vtctldata.ExecuteVtctlCommandResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.vtctldata.ExecuteVtctlCommandResponse.displayName = 'proto.vtctldata.ExecuteVtctlCommandResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.vtctldata.ExecuteVtctlCommandResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vtctldata.ExecuteVtctlCommandResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    event: (f = msg.getEvent()) && logutil_pb.Event.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vtctldata.ExecuteVtctlCommandResponse}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vtctldata.ExecuteVtctlCommandResponse;
  return proto.vtctldata.ExecuteVtctlCommandResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vtctldata.ExecuteVtctlCommandResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vtctldata.ExecuteVtctlCommandResponse}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new logutil_pb.Event;
      reader.readMessage(value,logutil_pb.Event.deserializeBinaryFromReader);
      msg.setEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.vtctldata.ExecuteVtctlCommandResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtctldata.ExecuteVtctlCommandResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtctldata.ExecuteVtctlCommandResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getEvent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      logutil_pb.Event.serializeBinaryToWriter
    );
  }
};


/**
 * optional logutil.Event event = 1;
 * @return {?proto.logutil.Event}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.prototype.getEvent = function() {
  return /** @type{?proto.logutil.Event} */ (
    jspb.Message.getWrapperField(this, logutil_pb.Event, 1));
};


/** @param {?proto.logutil.Event|undefined} value */
proto.vtctldata.ExecuteVtctlCommandResponse.prototype.setEvent = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.vtctldata.ExecuteVtctlCommandResponse.prototype.clearEvent = function() {
  this.setEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.vtctldata.ExecuteVtctlCommandResponse.prototype.hasEvent = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.vtctldata);
