/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.vtrpc.CallerID', null, global);
goog.exportSymbol('proto.vtrpc.ErrorCode', null, global);
goog.exportSymbol('proto.vtrpc.RPCError', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vtrpc.CallerID = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vtrpc.CallerID, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.vtrpc.CallerID.displayName = 'proto.vtrpc.CallerID';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vtrpc.CallerID.prototype.toObject = function(opt_includeInstance) {
  return proto.vtrpc.CallerID.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vtrpc.CallerID} msg The msg instance to transform.
 * @return {!Object}
 */
proto.vtrpc.CallerID.toObject = function(includeInstance, msg) {
  var f, obj = {
    principal: jspb.Message.getFieldWithDefault(msg, 1, ""),
    component: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subcomponent: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vtrpc.CallerID}
 */
proto.vtrpc.CallerID.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vtrpc.CallerID;
  return proto.vtrpc.CallerID.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vtrpc.CallerID} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vtrpc.CallerID}
 */
proto.vtrpc.CallerID.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrincipal(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setComponent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubcomponent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.vtrpc.CallerID} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtrpc.CallerID.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vtrpc.CallerID.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtrpc.CallerID.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPrincipal();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getComponent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getSubcomponent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string principal = 1;
 * @return {string}
 */
proto.vtrpc.CallerID.prototype.getPrincipal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.vtrpc.CallerID.prototype.setPrincipal = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string component = 2;
 * @return {string}
 */
proto.vtrpc.CallerID.prototype.getComponent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.vtrpc.CallerID.prototype.setComponent = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string subcomponent = 3;
 * @return {string}
 */
proto.vtrpc.CallerID.prototype.getSubcomponent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.vtrpc.CallerID.prototype.setSubcomponent = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vtrpc.RPCError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vtrpc.RPCError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.vtrpc.RPCError.displayName = 'proto.vtrpc.RPCError';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vtrpc.RPCError.prototype.toObject = function(opt_includeInstance) {
  return proto.vtrpc.RPCError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vtrpc.RPCError} msg The msg instance to transform.
 * @return {!Object}
 */
proto.vtrpc.RPCError.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vtrpc.RPCError}
 */
proto.vtrpc.RPCError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vtrpc.RPCError;
  return proto.vtrpc.RPCError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vtrpc.RPCError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vtrpc.RPCError}
 */
proto.vtrpc.RPCError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.vtrpc.ErrorCode} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.vtrpc.RPCError} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtrpc.RPCError.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vtrpc.RPCError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.vtrpc.RPCError.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = this.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ErrorCode code = 1;
 * @return {!proto.vtrpc.ErrorCode}
 */
proto.vtrpc.RPCError.prototype.getCode = function() {
  return /** @type {!proto.vtrpc.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.vtrpc.ErrorCode} value */
proto.vtrpc.RPCError.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.vtrpc.RPCError.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.vtrpc.RPCError.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.vtrpc.ErrorCode = {
  SUCCESS: 0,
  CANCELLED: 1,
  UNKNOWN_ERROR: 2,
  BAD_INPUT: 3,
  DEADLINE_EXCEEDED: 4,
  INTEGRITY_ERROR: 5,
  PERMISSION_DENIED: 6,
  RESOURCE_EXHAUSTED: 7,
  QUERY_NOT_SERVED: 8,
  NOT_IN_TX: 9,
  INTERNAL_ERROR: 10,
  TRANSIENT_ERROR: 11,
  UNAUTHENTICATED: 12
};

goog.object.extend(exports, proto.vtrpc);
